### ISSUE TITLE
how to fetch data from firestore and implement them in your datatable

### ISSUE THREAD

**Issue by jeedy20** [kechankrisna/flutter_responsive_table#1]
Please share the code from the above question

**Comment by kechankrisna** [comment]
You just can do a simple fetching data from firestore api, and shape it to list of map, everything would be fine.

**Comment by Bryanmuloni** [comment]
@kechankrisna I have also encountered a related issue when I check one item in the Row, it selects and adds more items in the table. I am using StreamBuilder to get a stream of data from Firestore.

**Comment by kechankrisna** [comment]
Can you share your snippet, so that I can defined the cause of error.

**Comment by Bryanmuloni** [comment]
@kechankrisna below is the class snippet where I am implementing the ResponsiveTable with data from Firestore:
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:empres_review_poc/models/original/classification_entry.dart';
import 'package:empres_review_poc/models/original/event_entry.dart';
import 'package:empres_review_poc/repository/event_repository.dart';
import 'package:empres_review_poc/theme/empres_colors.dart';
import 'package:empres_review_poc/theme/empres_textstyles.dart';
import 'package:flutter/material.dart';
import 'package:responsive_table/responsive_table.dart';

class EventsPending extends StatefulWidget {
  @override
  _EventsPendingState createState() => _EventsPendingState();
}

class _EventsPendingState extends State<EventsPending>
    with AutomaticKeepAliveClientMixin {
  final EventDataRepository _repository = EventDataRepository();
  Stream<QuerySnapshot> _eventStream;
  List<EventEntry> mEventList = List<EventEntry>();
  List<Map<String, dynamic>> mEventMapList = List<Map<String, dynamic>>();
  List<DatatableHeader> _headers = [
    DatatableHeader(
        headerBuilder: (value) {
          return Padding(
            padding: EdgeInsets.only(left: 2, right: 2),
            child: Container(
              height: 30,
              color: EmpresColors.eventTableHeaderGrayColor,
              child: Center(
                child: Text('Date',
                    style: EmpresTextStyles.eventTableHeaderTextStyle),
              ),
            ),
          );
        },
        value: "date",
        show: true,
        sortable: true,
        textAlign: TextAlign.center),
    DatatableHeader(
        headerBuilder: (value) {
          return Padding(
              padding: EdgeInsets.only(left: 2, right: 2),
              child: Container(
                height: 30,
                color: EmpresColors.eventTableHeaderGrayColor,
                child: Center(
                  child: Text('Country',
                      style: EmpresTextStyles.eventTableHeaderTextStyle),
                ),
              ));
        },
        value: "country",
        show: true,
        flex: 2,
        sortable: true,
        textAlign: TextAlign.left),
    DatatableHeader(
        headerBuilder: (value) {
          return Padding(
              padding: EdgeInsets.only(left: 2, right: 2),
              child: Container(
                height: 30,
                color: EmpresColors.eventTableHeaderYellowColor,
                child: Center(
                  child: Text('Animal Species',
                      style: EmpresTextStyles.eventTableHeaderDarkTextStyle),
                ),
              ));
        },
        value: "animal_species",
        show: true,
        sortable: true,
        textAlign: TextAlign.left),
    DatatableHeader(
        headerBuilder: (value) {
          return Padding(
              padding: EdgeInsets.only(left: 2, right: 2),
              child: Container(
                height: 30,
                color: EmpresColors.eventTableHeaderYellowColor,
                child: Center(
                  child: Text('Diseases',
                      style: EmpresTextStyles.eventTableHeaderDarkTextStyle),
                ),
              ));
        },
        value: "diseases",
        show: true,
        sortable: true,
        textAlign: TextAlign.left),
  ];

  List<int> _perPages = [5, 10, 15, 100];
  int _total = 100;
  int _currentPerPage = 5;
  int _currentPage = 1;
  List<Map<String, dynamic>> _source = List<Map<String, dynamic>>();
  List<Map<String, dynamic>> _selecteds = List<Map<String, dynamic>>();

  String _sortColumn;
  bool _sortAscending = true;
  bool _isLoading = true;
  bool _showSelect = true;

  String _convertSpecies(List<Classification> classificationList) {
    String species;
    if (classificationList != null) {
      for (Classification classification in classificationList) {
        species = classification.animalSpecies;
      }
    }
    return species;
  }

  void convertEventData(List<EventEntry> _events) {
    _total = _events.length;
    if (_events != null) {
      for (var event in mEventList) {
        mEventMapList.add({
          "id": event.eventStatus,
          "date": event.generalInfo.observationDate,
          "country": event.localityInfo.country,
          "animal_species":
              _convertSpecies(event.speciesInfo.speciesClassification),
          "diseases": event.diagnosisInfo.disease,
//                        "data": event
        });
      }
    }
    _initData();
  }

  _initData() async {
    _isLoading = true;

    if (mEventMapList != null) {
      _source.addAll(mEventMapList);
    }

    _isLoading = false;
  }

  @override
  void initState() {
    super.initState();
    _eventStream = _repository.getEventsFromFireStore();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return SingleChildScrollView(
        child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            mainAxisSize: MainAxisSize.max,
            children: [
          Container(
            margin: EdgeInsets.all(10),
            padding: EdgeInsets.all(0),
            constraints: BoxConstraints(
              maxHeight: 700,
            ),
            child: StreamBuilder<QuerySnapshot>(
                stream: _eventStream,
                builder: (context, snapshot) {
                  if (!snapshot.hasData) {
                    return Align(
                        alignment: Alignment.center,
                        child: CircularProgressIndicator(
                          valueColor: AlwaysStoppedAnimation<Color>(
                              EmpresColors.orangeVerticalTabColor),
                        ));
                  }
                  var data = snapshot.data.docs;
                  mEventList = data.map((snapshots) {
                    return EventEntry.eventFromSnapshot(snapshots);
                  }).toList();

                  if (mEventList != null) {
                    convertEventData(mEventList);
                  }
                  return ResponsiveDatatable(
                    title: Text('Pending Events',
                        style: EmpresTextStyles.eventTableTitleTextStyle),
                    actions: [
                      Row(
                        children: [
                          IconButton(
                              icon: Icon(Icons.search,
                                  color:
                                      EmpresColors.eventTableActionIconsColor),
                              onPressed: () {}),
                          IconButton(
                              icon: Icon(Icons.filter_alt_outlined,
                                  color:
                                      EmpresColors.eventTableActionIconsColor),
                              onPressed: () {
                                setState(() {});
                              }),
                          IconButton(
                              icon: Icon(Icons.cloud_download_outlined,
                                  color:
                                      EmpresColors.eventTableActionIconsColor),
                              onPressed: () {
                                setState(() {});
                              }),
                          IconButton(
                              icon: Icon(Icons.view_column_outlined,
                                  color:
                                      EmpresColors.eventTableActionIconsColor),
                              onPressed: () {
                                setState(() {});
                              })
                        ],
                      )
                    ],
                    headers: _headers,
                    source: _source,
                    selecteds: _selecteds,
                    showSelect: _showSelect,
                    autoHeight: false,
                    sortAscending: _sortAscending,
                    sortColumn: _sortColumn,
                    isLoading: _isLoading,
                    onSelect: (selected, eventMap) {
                      _onEventRowSelected(selected, eventMap);
                    },
                    onTabRow: (data) {
//                      update row color and display data in the overview
                      print('Row $data');
//                    Event selectedEvent = data['data'];
//                    StoreProvider.of<AppState>(context).dispatch(
//                        SetEventManagementOverviewEvent(event: selectedEvent));
                    },
                    onSort: (value) {
                      setState(() {
                        _sortColumn = value;
                        _sortAscending = !_sortAscending;
                        if (_sortAscending) {
                          _source.sort((a, b) =>
                              b["$_sortColumn"].compareTo(a["$_sortColumn"]));
                        } else {
                          _source.sort((a, b) =>
                              a["$_sortColumn"].compareTo(b["$_sortColumn"]));
                        }
                      });
                    },
                    onSelectAll: (value) {
                      if (value) {
                        _selecteds =
                            _source.map((entry) => entry).toList().cast();
                      } else {
                        _selecteds.clear();
                      }
                    },
                    footers: [
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 15),
                        child: Text("Rows per page:"),
                      ),
                      if (_perPages != null)
                        Container(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          child: DropdownButton(
                              value: _currentPerPage,
                              items: _perPages
                                  .map((e) => DropdownMenuItem(
                                        child: Text("$e"),
                                        value: e,
                                      ))
                                  .toList(),
                              onChanged: (value) {
                                setState(() {
                                  _currentPerPage = value;
                                });
                              }),
                        ),
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 15),
                        child:
                            Text("$_currentPage - $_currentPerPage of $_total"),
                      ),
                      IconButton(
                        icon: Icon(
                          Icons.arrow_back_ios,
                          size: 16,
                        ),
                        onPressed: () {
                          setState(() {
                            _currentPage =
                                _currentPage >= 2 ? _currentPage - 1 : 1;
                          });
                        },
                        padding: EdgeInsets.symmetric(horizontal: 15),
                      ),
                      IconButton(
                        icon: Icon(Icons.arrow_forward_ios, size: 16),
                        onPressed: () {
                          setState(() {
                            _currentPage++;
                          });
                        },
                        padding: EdgeInsets.symmetric(horizontal: 15),
                      )
                    ],
                  );
                }),
          ),
        ]));
  }

  void _onEventRowSelected(bool selected, Map eventEntry) {
    setState(() {
      print("Status: $selected and Value:$eventEntry ");
      if (selected) {
        _selecteds.add(eventEntry);
      } else {
        _selecteds.removeAt(_selecteds.indexOf(eventEntry));
      }
    });
  }
}

**Comment by Bryanmuloni** [comment]
@kechankrisna did you look at my snippet? What could be the problem?
