### ISSUE TITLE
background color to header

### ISSUE THREAD

**Issue by edwinmacalopu** [kechankrisna/flutter_responsive_table#12]
is it possible to put a background color to the header?

![header](https://user-images.githubusercontent.com/15043775/108218462-acecb780-7102-11eb-935a-8007b049cd16.png)

**Comment by kechankrisna** [comment]
version: 0.2.0+2 just release with these options:
* `headerDecoration`: decorate the data row
* `rowDecoration`: decorate the data row
* `selectedDecoration`: decorate the selected data row
* `headerTextStyle`: styling the header row
* `rowTextStyle`: styling the data row
* `selectedTextStyle`: styling the selected data row

![screenshot2](https://raw.githubusercontent.com/kechankrisna/flutter_responsive_table/master/screenshot/screenshot2.png)
