### ISSUE TITLE
Cannot fetch data - Unexpected Null Value

### ISSUE THREAD

**Issue by iamafzalhassan** [kechankrisna/flutter_responsive_table#18]
![Untitled](https://user-images.githubusercontent.com/44916328/148021701-c99cbc03-712d-4257-9af8-0f7c401885dd.png)
![Untitled2](https://user-images.githubusercontent.com/44916328/148021706-96acd14b-1022-427f-b2bb-060296584131.png)

I used only sample code in **pub.dev**

**Comment by kechankrisna** [comment]
> ![Untitled](https://user-images.githubusercontent.com/44916328/148021701-c99cbc03-712d-4257-9af8-0f7c401885dd.png) ![Untitled2](https://user-images.githubusercontent.com/44916328/148021706-96acd14b-1022-427f-b2bb-060296584131.png)
> 
> I used only sample code in **pub.dev**

I will fix asap, thank you for let me know

**Comment by MILANydv** [comment]
Why is this problem not solved? it is severe problem.

**Comment by kechankrisna** [comment]
> Why is this problem not solved? it is severe problem.

please try again with new example, I just updated.

**Comment by assylman** [comment]
@kechankrisna How did you solved this issue? Because my table is showing exactly the same result

**Comment by kechankrisna** [comment]
> @kechankrisna How did you solved this issue? Because my table is showing exactly the same result

Please make sure you are using null safety version or attach your snippets here, so we can observe it together
