### ISSUE TITLE
change background Select item

### ISSUE THREAD

**Issue by mbfakourii** [kechankrisna/flutter_responsive_table#19]
hi how change Selected item background ?

**Comment by kechankrisna** [comment]
version: 0.2.0+2 just release with these options:
* `headerDecoration`: decorate the data row
* `rowDecoration`: decorate the data row
* `selectedDecoration`: decorate the selected data row
* `headerTextStyle`: styling the header row
* `rowTextStyle`: styling the data row
* `selectedTextStyle`: styling the selected data row
