### ISSUE TITLE
selecteds don't work

### ISSUE THREAD

**Issue by gabsmoliv** [kechankrisna/flutter_responsive_table#2]
Hi i'm using mobx insted setstate to mark the checkbox and it doesn't work, but if a resize the screen the checkbox is marked.

Can help me? 

Sorry for bad english!

**Comment by gabsmoliv** [comment]
////// The properties

selecteds: _controller.selecteds,
 showSelect: true

////// The method onSelect

onSelect: (value, item) {
                        print("$value  $item ");
                        if (value) {
                           _controller.selecteds.add(item);
                        } else {
                            _controller.selecteds.removeAt(_controller.selecteds.indexOf(item));

                        }
                      },

///// Mobx 
@observable
  ObservableList<Map<String, dynamic>> selecteds = ObservableList<Map<String, dynamic>>().asObservable();

**Comment by kechankrisna** [comment]
Hi, sorry for being late, can you please send me the full example of your code, so that I can collaborate in real code.

**Comment by kechankrisna** [comment]
null safety was merged
