### ISSUE TITLE
change item divider color

### ISSUE THREAD

**Issue by mbfakourii** [kechankrisna/flutter_responsive_table#20]
hi how cheng item divider color

![Screenshot 2022-02-18 152322](https://user-images.githubusercontent.com/20955005/154722606-4d3d52c0-627c-4215-9a1b-57514f6711fe.png)

**Comment by kechankrisna** [comment]
version: 0.2.0+2 just release with these options:
* `headerDecoration`: decorate the data row
* `rowDecoration`: decorate the data row
* `selectedDecoration`: decorate the selected data row
* `headerTextStyle`: styling the header row
* `rowTextStyle`: styling the data row
* `selectedTextStyle`: styling the selected data row

**Comment by mbfakourii** [comment]
@kechankrisna  tanks for version: 0.2.0+2 but the divider can not be changed

**Comment by mbfakourii** [comment]
fixed ! tanks

```
headerDecoration: const BoxDecoration(border: Border(bottom: BorderSide(color: Colors.yellow, width: 1))),
rowDecoration: const BoxDecoration(border: Border(bottom: BorderSide(color: Colors.yellow, width: 1))),
```
