### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by ReniDelonzek** [kechankrisna/flutter_responsive_table#3]
I tested your library and it works great for small lists, but when I try to load a significant amount of data (I tested it with 10,000 rows, the application crashes), which could be solved with a lazy load

Taking advantage of the question, is there any way to explicitly define to use table instead of list?

**Comment by maurobotta** [comment]
+1

**Comment by SachinTanpure** [comment]
Yes we need lazy load feature

**Comment by kechankrisna** [comment]
null safety was merged
