### ISSUE TITLE
Fast import from json

### ISSUE THREAD

**Issue by maurobotta** [kechankrisna/flutter_responsive_table#4]
Hi

I have this list of json with 1000 / 10'000 records

[ {"Name":"Maria","Surname":"Red"} , {"Name":"Jack","Surname":"White"} ]

How i can import in temps List ?

List<Map<String, dynamic>> temps = List<Map<String, dynamic>>();

this don't work:
    final List<Map<String, dynamic>> temps = List<Map<String, dynamic>>.from(json.decode(sTextjson));

this 1 at time, is too slow:

    temps.add({
      "codice": "100",
      "Ragione Sociale": "$i\000$i",
      "Aggiuntiva": "Product Product Product Product $i",
      "Indirizzo": "Category-$i",
      "cap": "${i}0.00",
      "località": "20.00",
      "provincia": "${i}0.20",
      "telefono": "${i}0",
      "received": [i + 20, 150]
    });

**Comment by kechankrisna** [comment]
try new version with new dart and flutter
