### ISSUE TITLE
Table view instead of list view in mobile

### ISSUE THREAD

**Issue by SachinTanpure** [kechankrisna/flutter_responsive_table#9]
How to show table view instead of list view in mobile app?

**Comment by KDCinfo** [comment]
Flutter noob here. After running the demo code, and trying to understand why the layout was showing headers with every product, and not a tabular view like the demo GIF, I was wondering what I was doing wrong. But now your request makes sense! (I also couldn't see how one sort box on each product would relate to sorting by a specific 'header' (/column).) 

So what I'm seeing is a ListView of the products, and not a Table or DataTable, correct? Does that mean this package currently can't be used to represent tabular data for mobile? 

Welp, was trying to find something to help with a static/fixed header row coupled with sorting, but will go back to playing around with DataTables. I know there's another package for sticky table headers, but it doesn't mention sorting. 

![flutter_responsive_table](https://user-images.githubusercontent.com/495285/104833273-33844f80-584c-11eb-9db2-853d90bd9c4c.png)

**Comment by kechankrisna** [comment]
new version consists:
* `reponseScreenSizes`: the ScreenSize that will responsive as list view 
set empty if you want to keep table view for all screensize

**Comment by weebsproject** [comment]
> new version consists:
> 
> * `reponseScreenSizes`: the ScreenSize that will responsive as list view
>   set empty if you want to keep table view for all screensize

still having list view, not table view.


![image](https://user-images.githubusercontent.com/75978848/161226416-a59ff8e0-0ea9-40c9-bd75-c3ebc8f328f7.png)

any sample of code?
